version: '3.7'

services:
  bitwarden:
    image: bitwarden/server:latest
    container_name: bitwarden
    environment:
      - ADMIN_TOKEN=your_admin_token
      - DB_TYPE=mssql
      - DB_SERVER=bitwarden-db
      - DB_USERNAME=sa
      - DB_PASSWORD=your_db_password
      - DB_NAME=bitwarden
      - globalSettings__baseServiceUri__vault=https://vault.yourdomain.com
      - globalSettings__baseServiceUri__api=https://api.yourdomain.com
      - globalSettings__baseServiceUri__identity=https://identity.yourdomain.com
    depends_on:
      - bitwarden-db
      - bitwarden-redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - bitwarden-data:/data
    restart: unless-stopped

  bitwarden-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: bitwarden-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=your_db_password
    volumes:
      - bitwarden-db-data:/var/opt/mssql
    restart: unless-stopped

  bitwarden-redis:
    image: redis:6
    container_name: bitwarden-redis
    restart: unless-stopped

volumes:
  bitwarden-data:
  bitwarden-db-data:


